name: rail_one
description: "Knock Off of Rail One"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5        

  # Navigation
  go_router: ^13.0.0

  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Data / Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Utilities
  dartz: ^0.10.1            
  equatable: ^2.0.5
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.19
  local_auth: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mocktail: ^1.0.0  
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/translations/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/notosans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/notosans/NotoSans-Regular.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/railone.png
  adaptive_icon_background: "#0078D4"
  adaptive_icon_foreground: assets/icons/railone.png
  remove_alpha_ios: true

